export const JOB_POSITION_REQUEST = 'JOB_POSITION_REQUEST';
export const JOB_POSITION_SUCCESS = 'JOB_POSITION_SUCCESS';
export const JOB_POSITION_ERROR = 'JOB_POSITION_ERROR';

export const JOB_SALARIES_REQUEST = 'JOB_SALARIES_REQUEST';
export const JOB_SALARIES_SUCCESS = 'JOB_SALARIES_SUCCESS';
export const JOB_SALARIES_ERROR = 'JOB_SALARIES_ERROR';

export const OFFICES_REQUEST = 'OFFICES_REQUEST';
export const OFFICES_SUCCESS = 'OFFICES_SUCCESS';
export const OFFICES_ERROR = 'OFFICES_ERROR';
export const OFFICES_DATA_MODIFICATION = 'OFFICES_DATA_MODIFICATION';

export const EMPLOYEES_REQUEST = 'EMPLOYEES_REQUEST';
export const EMPLOYEES_SUCCESS = 'EMPLOYEES_SUCCESS';
export const EMPLOYEES_ERROR = 'EMPLOYEES_ERROR';

export const EMPLOYEES_ACCOUNT_DATA_REQUEST = 'EMPLOYEES_ACCOUNT_DATA_REQUEST';
export const EMPLOYEES_ACCOUNT_DATA_SUCCESS = 'EMPLOYEES_ACCOUNT_DATA_SUCCESS';
export const EMPLOYEES_ACCOUNT_DATA_ERROR = 'EMPLOYEES_ACCOUNT_DATA_ERROR';

export const FILE_FORM_UPLOADED = 'FILE_FORM_UPLOADED';
export const FILE_FORM_CLEAR = 'FILE_FORM_CLEAR';